---
- name: Install and Start Nginx on Localhost
  hosts: localhost
  become: yes  # Run as sudo
  # become_method: sudo
  # become_user: root
  # become_password: Kavana@13
  gather_facts: false

  tasks:
    - name: debug
      debug:
        msg: "hello:"

    - name: Ensure sudo is installed
      apk:
        name: sudo
        state: present
      become: no

    - name: Install Nginx
      apk:
        name: nginx
        state: latest
      become: no
          
      #delegate_to: localhost
      
    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      #delegate_to: localhost
      

