---
- name: Install and Start Nginx on Localhost
  hosts: localhost
  become: true  # Run as sudo
  # become_method: sudo
  # become_user: root
  # become_password: Kavana@13
  gather_facts: false

  tasks:
    - name: debug
      debug:
        msg: "hello:"

    # - name: update cache
    #   apt:
    #    update_cache = yes

    - name: Install Nginx
      ansible.builtin.apt:
          name: nginx
          state: latest

        
      #delegate_to: localhost
      
    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      #delegate_to: localhost
      

