---
- name: Install and Start Nginx on Localhost
  hosts: localhost
  become: no  # Run as sudo

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

