---
- name: Install and configure web server
  hosts: localhost
  become: yes  # Run as sudo
  # become_method: sudo
  # become_user: root
  # become_password: Kavana@13
  # gather_facts: false

  tasks:
    - name: debug
      debug:
        msg: "hello:"

    # - name: update cache
    #   apt:
    #    update_cache = yes

    - name: Install Nginx
      apt:
          name: nginx
          state: present
          update_cache: yes
      #delegate_to: localhost
      
    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
      #delegate_to: localhost
      

